services:
  - type: web
    name: starlinx-protoapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ADMIN_KEY
        value: starlab123
      - key: SECRET_KEY
        value: PLEASE-CHANGE-ME-THIS-IS-SECRET
