services:
  - type: web
    name: starlinx-web
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: starlinx-postgres
          property: internalConnectionString

databases:
  - name: starlinx-postgres
    plan: free
    region: oregon
    databaseName: starlinx
