services:
  - type: web
    name: starlinx-web
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port \
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: starlinx-postgres
          property: connectionString

databases:
  - name: starlinx-postgres
    region: oregon
    plan: free
